sudo: required

services:
  - docker

install:
  - docker build --tag bodsch/docker-collectd .
  - docker run --detach --name collectd bodsch/docker-collectd

script:
  - docker ps | grep -q collectd

after_success:
  - |
    [ "${TRAVIS_BRANCH}" == "master" ] && curl \
      --request POST \
      --header "Content-Type: application/json"  \
      --data '{"source_type":"Branch","source_name":"master"}' \
      https://registry.hub.docker.com/u/bodsch/docker-collectd/trigger/${DOCKER_HUB_TOKEN}/
