sudo: required

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=bodsch
    - BUILD_DATE=$(date +"%Y-%m-%d")
    - BUILD_VERSION=$(date +"%y%m")
    - COLLECTD_VERSION=$(./hooks/latest_release.sh)

jobs:
  include:
    - stage: build
      script:
        - make

    - stage: test
      script:
        - make compose-file
        - docker-compose build
        - docker-compose up -d
        - sleep 30s
        - make test
        - docker-compose down

    - stage: push docker image
      if: branch = master
      script:
        - make
        - docker tag ${USER}/docker-collectd:latest ${DOCKER_USERNAME}/docker-docker-collectd:latest
        - docker tag ${USER}/docker-collectd:latest ${DOCKER_USERNAME}/docker-docker-collectd:${COLLECTD_VERSION}
        #
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        #
        - docker push ${DOCKER_USERNAME}/docker-docker-collectd:latest
        - docker push ${DOCKER_USERNAME}/docker-docker-collectd:${COLLECTD_VERSION}
        #
        - docker logout
