sudo: required

services:
  - docker

env:
  global:
    - BUILD_DATE=$(date +"%Y-%m-%d")
    - COLLECTD_VERSION=${COLLECTD_VERSION:-5.8.0}

jobs:
  include:
    - stage: build, test and push docker image
      script:
        - make build
        - make start
        - docker ps | grep -q collectd
        - make stop
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker push ${DOCKER_USERNAME}/docker-collectd:${JOLOKIA_VERSION}
        - docker tag ${DOCKER_USERNAME}/docker-collectd:${JOLOKIA_VERSION} ${DOCKER_USERNAME}/docker-collectd:latest
        - docker push ${DOCKER_USERNAME}/docker-collectd:latest
