#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

cat << EOF > .env
BUILD_DATE=${BUILD_DATE}
BUILD_VERSION=${BUILD_VERSION}
BUILD_TYPE=${BUILD_TYPE}

COLLECTD_VERSION=${COLLECTD_VERSION}

GRAPHITE_HOST=graphite

EOF


docker-compose \
  --file compose/head.yml \
  --file compose/graphite.yml \
  --file compose/collectd.yml \
  config > docker-compose.yml
